### ISSUE TITLE
Training process

### ISSUE THREAD

**Issue by ManuCorrea** [BarisYazici/deep-rl-grasping#18]
Hello Baris, thanks a lot for sharing your work and your thesis. I have read through it and I find it really inspiring.

I am trying to replicate your success but I am having a hard time in accomplishing that, so I would like to ask you some questions in how to proceed.

I am trying to train it with SAC.

One of the problems I had is that after training it went straight to the edge of the box(edge well centered in the camera) but didn't even went down to picking it (as I saw that sometimes happened in your case), just static opening and closing, not even having some kind of reward so it makes me wonder why.

Here is one example of a failing one https://drive.google.com/file/d/1D_FRpUDJN2tLhNdzgUPp6ja4zrRB0aYf/view?usp=sharing

My success rate is 0.1 at most not matter how long it runs. I have notices that since my gripper is shorter the robot height was an important thing so it improved a bit after making it closer to the table.

I know in RL seeds of the environment can influence in the training so ones will converge or not, did you face this problem? How was your workflow for training? Did you execute many environments in parallel hopping to get a good result or it was relatively easy? Any advise? I would like to know as much as possible in order to get successful

**Comment by BarisYazici** [comment]
Hi ManuCorrea,

Reall cool that you read my thesis and trying to replicate it :) 

I had a similar problem in my training. It is definitely challenging to get it right when you are training for a new gripper in RL setup. I advise focusing on getting the right behavior in the simplest environment/setting first. You are training in a challenging environment. Start in the table environment with the curriculum learning setting set to easiest. This setting can be the robot's height. It is one of the most important parameters because when the gripper is closer to the table it has a high chance to grab the object with a random action. Try using the OnFloor scene in the scene config. There you don't have a hard object like the tray. I should say tray is a little tricky.


One question are you trying to use the already trained models in the repo? That would be interesting to if the trained model work at all on the different gripper.

**Comment by ManuCorrea** [comment]
Thanks a lot for your feedback I really appreciate it, hopefully that can lead me in a better direction, I will let you know.

I imagine it's hard to recall but more less how much iterations did you have to do to get it working? Once in the right direction was it easy to get the 96% success in validation?

Actually I haven't try them because my gripper is not a parallel gripper. Each "finger" is with angle input so I changed the model of the outputs. But I could give a try to get some insights.

Thank you very much again :)

**Comment by BarisYazici** [comment]
This is a screenshot from the results section of my thesis. You should probably expect to get over a 90% success rate after 500k timesteps. But don't oversee the reward if the agent is increasing the rewards you are probably on the right track algorithm and environment-wise.

<img width="929" alt="Screen Shot 2022-07-10 at 21 43 07" src="https://user-images.githubusercontent.com/11574709/178159739-9aef873f-ef76-46ef-879f-b261eb3787a5.png">


Try to use the simplified environment setting where the agent goes down with a constant velocity. After successfully learning the simplified environment in-floor the scene move towards the more difficult settings.
