### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by jamesking23** [BarisYazici/deep-rl-grasping#3]
I have trouble in running SAC with KUKA environment,after download Kuka_iia from bullet3:https://github.com/bulletphysics/bullet3/tree/master/examples/pybullet/gym/pybullet_data/kuka_iiwa.Kuka is not in the right position and the base is just at the location of initial gripper.Could you help me about this question if you are avaliable?

**Comment by BarisYazici** [comment]
You should not need to download the Kuka model from PyBullet. Since it is already included in the repo under the kukaExt branch. Just do `git checkout kukaExt `. There, under https://github.com/BarisYazici/deep-rl-grasping/tree/kukaExt/models folder you have all the necessary models you need to run the grasping model.
 
Could you clarify a couple of things as well?

- Are you running this repo or using PyBullet's example?
- Could you maybe post screenshots of the PyBullet GUI?
- If there is an error log in the terminal that would help a lot as well.

**Comment by BarisYazici** [comment]
Did you solve the problem?

**Comment by jamesking23** [comment]
Yes,I runned this program rightly,thanks for your help!

**Comment by jamesking23** [comment]
Hello，could you tell me  your e-mail address?

**Comment by BarisYazici** [comment]
I prefer to answer questions here on GitHub as it is public and everyone can benefit from it.
