### ISSUE TITLE
use other algorithm

### ISSUE THREAD

**Issue by jamesking23** [BarisYazici/deep-rl-grasping#4]
Hi，BarisYazici！
        1, Why did you use custom_obs_policy.create_augmented_nature_cnn(1) after EncodedDepthImgSensor?From my point of view，encoder is used for get a feature .
         2,I want to use   SAC Drq (paper：https://arxiv.org/abs/2004.13649，code：https://github.com/denisyarats/drq ) to run your environment，what should I do？Should I encode the image before env = DummyVecEnv([lambda:  TimeFeatureWrapper(gym.make('gripper-env-v0', config=config))])？

**Comment by BarisYazici** [comment]
1. We use the custom obs policy to extract the raw image observation from gripper width observation. We need to extract the image observation and pass it through a convolutional neural network. However, the gripper width information should not pass through this convolutional layer. Since stable baselines do not support [dictionary observation](https://github.com/hill-a/stable-baselines/issues/133) we need to concatenate the gripper width information to the image observation. We use the convolutional layer to process the image observation and then add the gripper information to the output of the convolutional neural network.
![depthobs](https://user-images.githubusercontent.com/11574709/113265645-ac843680-92d4-11eb-86bf-74eb12a477b6.jpeg)
2. I guess they are using some kind of a CNN to encode the image observation. In this case, I would suggest you first omit the gripper width information and just return the raw depth observation. This function returns only the depth. Then try if the algorithm works. You don't need to use the dummy vector env or time feature wrapper. Just use `env = gym.make('gripper-env-v0', config=config)` to instantiate the environment and pass it to the drq.

**Comment by jamesking23** [comment]
It helps me a lot，thank you！
